### ISSUE TITLE
docs: CustomResourceDefinition is mandatory? + A tip for kops users

### ISSUE THREAD

**Issue by mrtyler** [miracle2k/k8s-snapshots#34]
Hello,

I wanted to check my understanding on a couple things before I offer a PR.

### CustomResourceDefinition is mandatory?

I have a k8s 1.8.0 cluster. Following the README I deployed k8s-snapshots (both v2.0 and dev), annotated a Persistent Volume, and hit this error:

```
2017-10-05T04:02:34.136420193Z requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://100.64.0.1:443/apis/k8s-snapshots.elsdoerfer.com/v1/snapshotrules?watch=true
```

`k8s-snapshots.elsdoerfer.com` was not in the output of `curl https://100.64.0.1:443/apis/`.
I deployed the CustomResourceDefinition from the "Manual snapshot rules" section later in the README and the error went away.

Is it expected that the CRD is mandatory, at least in k8s 1.7+? If so, I'll update the docs. If not, I can provide more detail about my setup if this is a bug worth investigating.

### A tip for kops users

We use [kops](https://github.com/kubernetes/kops/) to manage our k8s cluster. k8s-snapshots didn't work out of the box due to a permissions issue. If you agree, I'd like to add a tip about this to the README for fellow kops users:

k8s-snapshots need EBS and S3 permissions to take and save snapshots. Under the kops IAM Role scheme, only Masters have these permissions. The easiest solution is to run k8s-snapshots on Masters.

To run on a Master, we need to:
* overcome a Taint -- see https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/

* specify that we require a Master -- see https://kubernetes.io/docs/concepts/configuration/assign-pod-node/

To do this, add the following to the above manifest for the k8s-snapshots Deployment:

```
spec:
  ...
  template:
  ...
    spec:
      ...
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Equal"
        value: ""
        effect: "NoSchedule"
      nodeSelector:
        kubernetes.io/role: master
```

### Thanks

k8s-snapshots is cool! :)
