### ISSUE TITLE
VolumeClaimTemplates

### ISSUE THREAD

**Issue by TC-robV** [miracle2k/k8s-snapshots#97]
Anyway to get this to work for a VolumeClaimTemplate in a StatefulSet?
I tried the following with no luck. Curious if anyone got it working somehow?

```
  volumeClaimTemplates:
  - metadata:
      name: storage
      annotations:
        backup.kubernetes.io/deltas: P1D P30D
    spec:
      storageClassName: ssd-retain
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: 25Gi
```
