### ISSUE TITLE
no matches for kind "Deployment" in version "extensions/v1beta1"

### ISSUE THREAD

**Issue by chrisfosterelli** [miracle2k/k8s-snapshots#99]
On recent kubernetes `extensions/v1beta1` does not support `Deployment`s. It has to be changed to `apiVersion: apps/v1`. It also needs a `spec.selector` field. E.g.

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-snapshots
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-snapshots
  template:
    metadata:
      labels:
        app: k8s-snapshots
    spec:
      serviceAccountName: k8s-snapshots # <- If used
      containers:
        - name: k8s-snapshots
          image: elsdoerfer/k8s-snapshots:latest
```

Perhaps the README would benefit from an update?
